### ISSUE TITLE
Problem getting filtered partial completions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-shell#14]
OS: Mac
Install method: pip install in a virtualenv
Python version: 2.7.12
Shell: bash

When I type: `group create -l` the completions appear in blue. If I then start to type `we`, my completions completely disappear and never come back. Also, if I [tab][tab] it does not complete (though it would outside the shell).

**Comment by derekbekoe** [comment]
Same on Ubuntu 14.04.

<img width="339" alt="screen shot 2017-04-05 at 3 01 51 pm" src="https://cloud.githubusercontent.com/assets/16448634/24729036/46967a6c-1a11-11e7-96c0-f50836b0da06.png">
