### ISSUE TITLE
Command option suggestions

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-shell#22]
OS: Mac
Install method: pip install in a virtualenv
Python version: 2.7.12
Shell: bash

When I type `vm create ` I don't get any suggestions for what to type next. If I type - I'll get the short options and then -- will give me the long options. It might be nice to recognize that you've resolved to a command and immediately load the option help box. 

Also, the options are not sorted in any kind of order, making it very difficult to know what you should supply next. When you run -h there is a kind of ordering so that the most important things are at the top (for example, resource-group and name). You might look to emulate that in the shell.

**Comment by oakeyc** [comment]
PR #77
