### ISSUE TITLE
Feedback on History Suggestion

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-shell#28]
OS: Mac
Install method: pip install in a virtualenv
Python version: 2.7.12
Shell: bash

When I type: `group create -l westus -n myrg` and then `group create` I get the rest of my previous command as a suggestion. It wasn't clear to me how to use that suggestion. I tried just pressing Enter and of course that didn't work. I tried Tab and that didn't work. It wasn't obvious to me that I needed to press the right arrow key. 

Since the suggestion appears in largely the same color (dark grey) as a manually typed command (where the values are dark grey) that may have contributed to the confusion.

Two suggestions:
 - Use a light grey for the history suggestion
 - Instead of making the right arrow take the entire suggestion to the end, consider making it use the "next" item. So, if I had `foo -a a -b b -c c`, when I type `foo[right]` I would get `foo -a a` instead of `foo -a a -b b -c c`.

**Comment by oakeyc** [comment]
PR #96 adds color options to make the appended suggestion less camouflaged
