### ISSUE TITLE
Ctrl+C on "group wait" should not exit the shell

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-cli-shell#29]
Currently, it waits:
![image](https://cloud.githubusercontent.com/assets/1050156/24729067/59dcdb5c-1a11-11e7-9105-2c9382cee3c0.png)

But if i changed my mind and want to quit this command, this breaks the shell as well:
![image](https://cloud.githubusercontent.com/assets/1050156/24729085/73063196-1a11-11e7-9cc8-c0f5ac0c4ee1.png)

Should not break the shell, but just stop the command

**Comment by oakeyc** [comment]
#23

**Comment by derekbekoe** [comment]
@oakeyc I think it's related but not a duplicate.
In here, @lmazuel wants to be able to exit the current running command and still be in the shell.
