### ISSUE TITLE
Feedback on scope feature

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-shell#34]
A few points:

1. It wasn't clear to me what this feature did. After chatting with you, it basically functions like cd to traverse the CLI "tree". The concept is great! The usability can be improved.

2. IMO it should not attempt to run the command. The cd analogy applies here. If I typed C:/foo/bar/this.exe, my program would execute and I would end up at C:/.  If I wanted to change the "scope" I would cd C:/foo/bar and the run this.exe.  If I tried `cd C:/foo/bar/this.exe` I'd get an error. Since people are used to navigating with cd (and cd .., which I'd recommend in lieu of ^^), I would follow this pattern.

3. You should validate the "path" when setting scope.  If I do `%%network` and `%%noodle` it will happily set this even though this is not valid. 

4. If I want to have a default scope of `network vnet`, I could not get this to work. I tried:

  a. `%%network vnet`
  b. `%%"network vnet"` 
  c. `%%network %%vnet`

I would suggest making option a work.

5. I would suggest making ^^ work like cd. Instead of ^^ going back to root, I would overload %% to accept `%%..` for going back.

**Comment by derekbekoe** [comment]
I'd like it to work like `cd`

**Comment by oakeyc** [comment]
PR #74
