### ISSUE TITLE
Non-interactive login doesn't work

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-shell#44]
OS: Mac
Install method: pip install in a virtualenv
Python version: 2.7.12
Shell: bash

I tried `login -u {my-user}` I get an error. I can only successfully login using the interactive device flow.

**Comment by tjprescott** [comment]
As a workaround you can enable this scenario with #:
`#az login -u {my-user}`

**Comment by oakeyc** [comment]
Did your user name and/or password include the substring 'az'?

**Comment by tjprescott** [comment]
The username did:  `blahblah@azureblahblah.blahblahblah`
